#!/usr/bin/env bash
# This bash script installs nginx on a server

apt-get update
apt-get install -y nginx

service nginx restart
systemctl enable nginx

#echo "Hello World!" | sudo tee /var/www/html/index.html

echo "
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location / {
        return 200 'Hello World!';
        add_header Content-Type text/plain;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
