#!/usr/bin/env bash
# This bash script installs nginx on a server

apt-get update
apt-get install -y nginx

service nginx restart
systemctl enable nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
