#!/usr/bin/env bash
# This bash script installs nginx on a server

apt-get update
apt-get install -y nginx

systemctl enable nginx

echo "Hello World!                 " > /var/www/html/index.html
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
