#!/usr/bin/env bash
# this script fixes an nginx installation
apt install -y lsof
kill -QUIT "$(lsof -i -P -n | grep LISTEN | grep nginx | awk '{print $2}' | head -n 1)"
service nginx start
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx reload
