#!/usr/bin/env bash
# Fixes Nginx user issue

if [ ! -x /usr/sbin/nginx ]; then
  sudo apt-get update
  sudo apt-get install nginx -y
fi

sudo chown -R nginx:nginx /var/www/html /etc/nginx
# Create an Nginx configuration file to listen on port 8080
cat <<EOL | sudo tee /etc/nginx/sites-available/nginx_config
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    root /var/www/html;
    index index.html;

    location / {
        add_header X-Served-By "nginx";
    }
}
EOL

# Create a symbolic link to enable the configuration
if [ -L '/etc/nginx/sites-enabled/nginx_config' ]; then
	sudo rm /etc/nginx/sites-enabled/nginx_config
fi
sudo ln -s /etc/nginx/sites-available/nginx_config /etc/nginx/sites-enabled/

# Set Nginx to run as the nginx user
sudo sed -i 's|^user .*$|user nginx;|' /etc/nginx/nginx.conf

sudo service nginx restart
